### PR TITLE
add alias table to all genes with biosamples

### LINKED ISSUE #12: update gene lists
When the portal is updated with new data, TSPAN6 will no longer be the first record displayed on the gene page because no new files were associated with this gene. Instead, the NUS1 gene (ENSG00000153989) will be the top hit because it was the last gene to be linked to a new file during this release cycle.

I think it would be good to add a few more genes to the list, especially ENSG00000153989 so it will be easy to demo. 

We might also want to thinking about adding these annotations to hundreds or thousands of genes..

### LINKED ISSUE #19: HGCN not quite right
In `ensemble_genes.tsv` the HGCN id is reported twice for any given gene. See TSPAN6 example:
- `[Source:HGNC Symbol;Acc:HGNC:11858]`
- `"HGNC:11858"`

```
ENSG00000000003	TSPAN6	tetraspanin 6 [Source:HGNC Symbol;Acc:HGNC:11858]	["ENTREZ:7105", "HGNC:11858", "MIM:300191", "NM_001278740", "NM_001278741", "NM_001278742", "NM_001278743", "NM_003270", "NP_001265669", "NP_001265670", "NP_001265671", "NP_001265672", "NP_003261", "T245", "TM4SF6", "TSPAN-6", "TSPAN6", "XM_011531018", "XP_011529320", "tetraspanin 6"]	NCBI:txid9606
```

The code to extract the HGNC id and create hyperlinks to the appropriate pages  is in `build-markdown-pieces-gene-translate.py`. The code look right, but the output is defaulting to value error of "None" instead of returning the ID, even though the ID is there for every gene.

Screen Shot 2022-07-01 at 9 18 50 AM

(Note, in #15, I rotated the table so that the column names are now the row names, and I tried to directly call the URL instead of using the shortlink).

See

176743882-ffb037d3-de83-47d4-a9e0-d99b2f16cbd0
Screen Shot 2022-07-01 at 9 25 31 AM

### LINKED ISSUE #22: not all genes in dev are in the ensembl_genes.tsv reference list
These genes have pages in the dev version portal but they do not have entries in `ensembl_genes.tsv`

```
 [1] "ENSG00000093134" "ENSG00000105501" "ENSG00000161133"
 [4] "ENSG00000164393" "ENSG00000184293" "ENSG00000188707"
 [7] "ENSG00000203812" "ENSG00000214534" "ENSG00000221995"
[10] "ENSG00000225932" "ENSG00000244693" "ENSG00000256374"
[13] "ENSG00000263464"
```

This causes problems when trying to create the alias table

```
Running with term: gene
Using output dir output_pieces_gene/00-alias for pieces.
Loaded 24620 reference IDs from data/validate/ensembl_genes.tsv
ERROR: requested input id ENSG00000256374 not found in ref_id_list
[Fri Jul  1 10:46:40 2022]
Error in rule gene_json_alias_widget:
    jobid: 6
    output: output_pieces_gene/00-alias
    shell:
        
        scripts/build-markdown-pieces-gene-translate.py gene data/inputs/DEV_PORTAL__available_genes__2022-07-01.txt data/inputs/Homo_sapiens.gene_info_20220304.txt_conv_wNCBI_AC.txt             --widget-name alias_table             --output-dir output_pieces_gene/00-alias
    
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job gene_json_alias_widget since they might be corrupted:
output_pieces_gene/00-alias
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-07-01T104626.044530.snakemake.log
```

### PR DESCRIPTION
**Pull request by raynamharris**
new branch off #14 

updated the snakefile to point to a different list of genes. two genes werent in the human table so they were removed, but i got this error message

```
Traceback (most recent call last):
  File "/Users/raynamharris/GitHub/update-content-registry/scripts/build-markdown-pieces-gene-translate.py", line 146, in <module>
    sys.exit(main())
  File "/Users/raynamharris/GitHub/update-content-registry/scripts/build-markdown-pieces-gene-translate.py", line 141, in main
    cfde_common.write_output_pieces(output_dir, args.widget_name,
  File "/Users/raynamharris/GitHub/update-content-registry/scripts/cfde_common.py", line 33, in write_output_pieces
    fp.write(md)
TypeError: write() argument must be str, not list
[Thu Jun 30 10:28:14 2022]
Error in rule gene_json_alias_widget:
    jobid: 9
    output: output_pieces_gene/30-alias
    shell:
        
        scripts/build-markdown-pieces-gene-translate.py gene data/inputs/genes-with-biosamples-30.06.2022.txt data/inputs/Homo_sapiens.gene_info_20220304.txt_conv_wNCBI_AC.txt             --widget-name alias_table             --output-dir output_pieces_gene/30-alias
    
        (one of the commands exited with non-zero exit code; note that snakemake uses bash strict mode!)

Removing output files of failed job gene_json_alias_widget since they might be corrupted:
output_pieces_gene/30-alias
Shutting down, this might take some time.
Exiting because a job execution failed. Look above for error message
Complete log: .snakemake/log/2022-06-30T102806.754156.snakemake.log
```

### CODE REVIEW

**Comment by raynamharris** [comment]
the goal is to have this on every page
Screen Shot 2022-06-30 at 10 41 06 AM

**Comment by raynamharris** [comment]
1. There is already a link to the NCBI gene page in this table, so I can actually remove the scripts and snakemake rules created in #3 and #4.
2. Also, I think we could probably incorporate the Appyter links into this table instead of having a stand alone header with text.
3. Finally, it might be worth rotating the table so that the headers are row names, much like the top of the gene page, or maybe simply reordering the annotations would work well


Screen Shot 2022-06-30 at 10 42 17 AM

Screen Shot 2022-06-30 at 10 41 06 AM


example-gene-appyter-page

**Comment by ctb** [comment]
error fixed in 9529b17 - there are some missing ensembl IDs in the translation table.

**Comment by raynamharris** [comment]
yea! working

Screen Shot 2022-06-30 at 11 43 42 AM

**Comment by raynamharris** [comment]
hmm, i move the alias table to the top of the list of pieces to build in the snakmake file, but the order didn't change

Screen Shot 2022-06-30 at 12 00 00 PM


Screen Shot 2022-06-30 at 12 00 24 PM

**Comment by raynamharris** [comment]
rotated the alias table

Screen Shot 2022-06-30 at 1 09 07 PM

**Comment by raynamharris** [comment]
pretty happy with this... 7500 genes have alias tables and appyter links (see #14)
Screen Shot 2022-06-30 at 1 50 11 PM

**Comment by raynamharris** [comment]
not sure why the HGNC terms aren't showing up

**Comment by raynamharris** [comment]
trouble shooting the HGCN term... it's showing up as "None" instead of "3005" and redirecting to https://www.genenames.org/data/gene-symbol-report/#!/hgnc_id/HGNC:3005

Screen Shot 2022-06-30 at 2 37 17 PM

Screen Shot 2022-06-30 at 2 38 33 PM

Screen Shot 2022-06-30 at 2 37 31 PM

**Comment by ctb** [comment]
> hmm, i move the alias table to the top of the list of pieces to build in the snakmake file, but the order didn't change

yes, it's sorted using alphabetical/lexicographic order, so `00-appyter` will always go first, etc.

**Comment by raynamharris** [comment]
Okay, I updated the snakemake file to create the alias table and appyter links for **12,506** genes! 

13 genes were in dev but not in the ensemble_genes.tsv file, so I removed those. It might be better to do some sort of test rather than delete entries.... See #22

**Comment by raynamharris** [comment]
this is ready for review. The last thing was to update the gallery images to reflect my changes to the alias table and the Appyter text

example-alias-table
example-gene-appyter-page

**Review by abradyIGS — APPROVED** [review]
looks fine to me, although i went a little cross-eyed looking at the file diff

**Comment by raynamharris** [comment]
yes, github has a hard time with repeating elements, which you get in snakefiles with lots of rules

**Pull request merged**
