### PR TITLE
add MetGene

### PR DESCRIPTION
**Pull request by raynamharris**
add MetGene to the table of aliases and links for genes

Screen Shot 2022-08-09 at 10 59 57 AM

### CODE REVIEW

**Comment by raynamharris** [comment]
added iframe. 

Screen Shot 2022-08-10 at 1 47 32 PM

**Comment by raynamharris** [comment]
added an image but it is quite large.... 


Screen Shot 2022-08-10 at 4 09 53 PM


the markdown input looks like this:

```
f"""::: iframe [**Gene-centric Metabolomics Information Retrieval Tool (via MetGene API)**](https://bdcw.org/MetGENE/mgSummary.php?species=hsa&ENSEMBL={cv_id}){{width=\"1200\" height=\"100\" style=\"border: 1px solid black;\" caption-style=\"font-size: 24px;\" caption-link=\"v\" caption-target=\"_blank\"}} \n:::\n\n![Image](https://bdcw.org/MetGENE/mgSummary.php?species=hsa&ENSEMBL={cv_id}&viewType=png)\n\nMore information is available on the Gene-centric Metabolomics Information Retrieval Tool query page for [{cv_id}](https://bdcw.org/MetGENE/index.php?species=hsa&GeneIDType=ENSEMBL&GeneInfoStr={cv_id}&anatomy=NA&disease=NA&phenotype=NA)."""
```

the markdown output looks like this:

```
::: iframe [**Gene-centric Metabolomics Information Retrieval Tool (via MetGene API)**](https://bdcw.org/MetGENE/mgSummary.php?species=hsa&ENSEMBL=ENSG00000000419){width="1200" height="100" style="border: 1px solid black;" caption-style="font-size: 24px;" caption-link="v" caption-target="_blank"} 
:::

![Image](https://bdcw.org/MetGENE/mgSummary.php?species=hsa&ENSEMBL=ENSG00000000419&viewType=png)

More information is available on the Gene-centric Metabolomics Information Retrieval Tool query page for [ENSG00000000419](https://bdcw.org/MetGENE/index.php?species=hsa&GeneIDType=ENSEMBL&GeneInfoStr=ENSG00000000419&anatomy=NA&disease=NA&phenotype=NA)
```

**Comment by raynamharris** [comment]
preview  of combined image and table

for genes with metgene info
Screen Shot 2022-08-11 at 11 46 27 AM

without info

Screen Shot 2022-08-11 at 11 47 16 AM

**Comment by raynamharris** [comment]
added link to iframe, removed link from table. looking great :)
Screen Shot 2022-08-11 at 12 44 32 PM

**Review by jessicalumian — APPROVED** [review]

**Pull request merged**
