### PR TITLE
[MRG] generate URLs for lists of valid IDs dynamically

### PR DESCRIPTION
**Pull request by ctb**
So https://github.com/nih-cfde/update-content-registry/pull/68 does a really nice job of addressing #70 but the new `scripts/retrieve-ids.sh` file implements some behavior that Snakemake can do more nicely (in terms of integrating into file date checking, etc.)

This PR demonstrates how to shift that behavior back into Snakemake, and as a bonus (?) removes the "valid ID" files from github.

### CODE REVIEW

**Comment by raynamharris** [comment]
I like this a lot! I was reading about lamba and parms but wasn't quite sure how to use them. 

The only thing is that that the rule all isn't quite working to incorporate the retrieve and retrieve_term_wc rules. I had to run `make retrieve` to get the list to successfully run `make`.  This is why the action failed.

**Comment by ctb** [comment]
ahh, I see.

The simplest and most correct (but also most tedious) way to deal with this is to add explicit references to `data/validate/TERM.csv` to all the rules that use them - e.g. add `data/validate/gene.csv` to the inputs for rule g`ene_json_alias_widget`. I'll do that when I have a moment, or you can ;)

**Comment by ctb** [comment]
fixed! ready for merge I think.

**Comment by raynamharris** [comment]
works great now. thanks! the snakemake output is very nice as well.

**Pull request merged**
