### PR TITLE
august updates

### LINKED ISSUE #54: add GTEx widget pages to all genes for which GTEx has information
right now the GTEx widget page is only on ~10 genes; we should expand this.

we need to get a list of genes from GTEx.

### PR DESCRIPTION
**Pull request by raynamharris**
1. replaces `compound_IDs_GlyTouCan_test.txt` with `compound_IDs_GlyTouCan.txt` to annotate thousands of compounds. 
1. adds  `gene_IDS_for_gtex.txt` to annotate thousands of genes with gtex api foo
1. rm old gene lists
1. updated script to produce table of overlaps of annotations on genes
1. added script to produce table of overlapping compound annotations
1. add H2 header "Resources" to all pages. replaces other headers with bold text
1. add names to linked diseases, genes, and proteins.

### CODE REVIEW

**Comment by raynamharris** [comment]
Ready for review. See list of pages to check in #59

Here are some screen shots
Screen Shot 2022-08-23 at 5 18 56 PM
Screen Shot 2022-08-23 at 5 40 03 PM
Screen Shot 2022-08-23 at 5 42 19 PM
Screen Shot 2022-08-23 at 5 42 48 PM
Screen Shot 2022-08-23 at 5 43 00 PM
Screen Shot 2022-08-23 at 5 43 06 PM

Screen Shot 2022-08-23 at 5 13 25 PM

**Comment by raynamharris** [comment]
got it working for gene names but not protein names... will continue tomorrow

Screen Shot 2022-08-25 at 4 43 50 PM

**Comment by raynamharris** [comment]
yea! ready to merge. dieases looking great now :) 

Screen Shot 2022-08-26 at 10 21 31 AM

**Review by abradyIGS — APPROVED** [review]
I approve.

**Pull request merged**
