### PR TITLE
add compound files and markdown content

### LINKED ISSUE #16: annotate compounds
update aug 12

annotations to add 
- [x] LINCS
- [x] PubChem
- [x] Glycan
- [x] DrugCentral

see #46 and #33 

---

I'd like to add some external links for the compounds but the ID field is interesting... because the ID is numeric for PUBMed but a strong for GlyTouCan

https://github.com/nih-cfde/published-documentation/wiki/TableInfo:-compound.tsv

Screen Shot 2022-06-30 at 2 05 05 PM

Screen Shot 2022-06-30 at 2 18 32 PM

So, we would need like an if/else statement to send the {ID} to either https://glytoucan.org/Structures/Glycans/{ID}  or https://pubchem.ncbi.nlm.nih.gov/compound/{ID} as appropriate

Screen Shot 2022-06-30 at 2 16 19 PM

Screen Shot 2022-06-30 at 2 14 34 PM

### PR DESCRIPTION
**Pull request by raynamharris**
This PR does a few things.  Closes #16 

adds input files, alias files, and scripts for PubChem, Drug Central, Glygan, and LINCs

### CODE REVIEW

**Comment by raynamharris** [comment]
Currently, adds a sentence starting with "External links: ..." to either GlyGen or PubChem page. 

Screen Shot 2022-08-08 at 11 07 51 AM
Screen Shot 2022-08-08 at 2 13 29 PM

**Comment by raynamharris** [comment]
I have updated the markdown text for Glycans so now it looks like this 

Screen Shot 2022-08-09 at 12 09 34 PM

**Comment by raynamharris** [comment]
added glycan images and links for compounds referred to by compound id
Screen Shot 2022-08-09 at 4 49 11 PM

**Comment by raynamharris** [comment]
summary of annotations on staging: **73,498**

Screen Shot 2022-08-12 at 4 14 48 PM

would like to figure out how to reduce drug image but oh well. 

need to merge #46 first, then fix conflicts

**Review by jessicalumian — APPROVED** [review]

**Pull request merged**
